#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

# Stash any unstaged changes
git stash -q --keep-index

# Pull any changes from the remote with rebase
git pull --rebase origin main

# Restore stashed changes
git stash pop -q