#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

npx eslint . || (echo "ESLint checks failed!" && exit 1)
npx prettier --write . || (echo "Prettier checks failed!" && exit 1)
npx lint-staged || (echo "Lint-staged checks failed!" && exit 1)